# Generated by Django 5.0.3 on 2024-03-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('auc_link', models.TextField()),
                ('title', models.TextField()),
                ('auc_name', models.TextField()),
                ('auc_number', models.TextField()),
                ('auc_date', models.DateField()),
                ('year_car', models.TextField()),
                ('mileage', models.TextField()),
                ('color', models.TextField()),
                ('options', models.TextField()),
                ('the_body', models.TextField()),
                ('volume', models.TextField()),
                ('cpp', models.TextField()),
                ('estimation', models.TextField()),
                ('cooling', models.TextField()),
                ('set', models.TextField()),
                ('result', models.TextField()),
                ('start_price', models.TextField()),
                ('transmission', models.TextField()),
                ('location_auction', models.TextField()),
                ('year', models.TextField()),
                ('alt_color', models.TextField()),
                ('condition', models.TextField()),
                ('fuel', models.TextField()),
                ('equipment', models.TextField()),
                ('deadline_for_the_price_offer', models.TextField()),
                ('day_of_the_event', models.TextField()),
                ('number_of_sessions', models.TextField()),
                ('auc_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('passport_num', models.TextField()),
                ('tel_num', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('payer', models.TextField()),
                ('seller', models.TextField()),
                ('date_form', models.DateField()),
                ('date_pay', models.DateField()),
                ('sum', models.IntegerField()),
                ('check_document', models.TextField()),
                ('assigning', models.TextField()),
                ('scan', models.TextField()),
                ('type', models.TextField(choices=[('Оплата авто в Японии', 'Оплата авто в Японии'), ('Оплата услуг ТК', 'Оплата услуг ТК'), ('Оплата таможенного взноса(ПТД)', 'Оплата таможенного взноса(ПТД)'), ('Оплата услуг лаборатории(СБТС)', 'Оплата услуг лаборатории(СБТС)'), ('Оплата услуг компании', 'Оплата услуг компании')])),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('full_name', models.TextField()),
                ('job_title', models.TextField(choices=[('Клиент-менеджер', 'Менеджер'), ('Логист', 'Логист'), ('HR', 'HR'), ('Бухгалтер', 'Бухгалтер'), ('Оперативник', 'Оперативник')])),
                ('phone_number', models.TextField()),
                ('passport', models.TextField(unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCar',
            fields=[
                ('id_photo', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField()),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.car')),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id_trans', models.AutoField(primary_key=True, serialize=False)),
                ('trans_comp', models.TextField()),
                ('departure_point', models.TextField()),
                ('destination_point', models.TextField()),
                ('date_form', models.DateField()),
                ('date_shipment', models.DateField()),
                ('date_receive', models.DateField()),
                ('id_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('comment', models.TextField()),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.car')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.customer')),
                ('id_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.invoice')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.worker')),
            ],
        ),
    ]
