# Generated by Django 5.0.3 on 2024-03-13 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('auc_link', models.TextField()),
                ('name', models.TextField()),
                ('price_start', models.IntegerField()),
                ('price_buy', models.IntegerField()),
                ('auc_list', models.TextField()),
                ('SBTS', models.TextField()),
                ('PTD', models.TextField()),
                ('auc_buy_date', models.DateField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('passport_num', models.TextField()),
                ('tel_num', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('payer', models.TextField()),
                ('receipent', models.TextField()),
                ('date_form', models.DateField()),
                ('date_pay', models.DateField()),
                ('sum', models.IntegerField()),
                ('check_to_client', models.TextField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('job_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id_trans', models.AutoField(primary_key=True, serialize=False)),
                ('trans_comp', models.TextField()),
                ('departure_point', models.TextField()),
                ('destination_point', models.TextField()),
                ('date_form', models.DateField()),
                ('date_shipment', models.DateField()),
                ('date_receive', models.DateField()),
                ('id_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.invoices')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('comment', models.TextField()),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.car')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.customer')),
                ('id_invoice_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.invoices')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.worker')),
            ],
        ),
    ]
