# Generated by Django 5.0.3 on 2024-03-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_for_page',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('auction_data', models.TextField()),
                ('car_options', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
