# Generated by Django 5.0.3 on 2024-03-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_form',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_pay',
            field=models.TextField(),
        ),
    ]
