# Generated by Django 5.0.3 on 2024-03-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.TextField(),
        ),
    ]
