# Generated by Django 5.0.3 on 2024-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ptd',
            field=models.FileField(null=True, upload_to='ptd/'),
        ),
    ]
