# Generated by Django 5.0.3 on 2024-03-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('От 0 до 3 лет', 'От 0 до 3 лет'), ('От 3 до 5 лет', 'От 3 до 5 лет'), ('От 5 лет', 'От 5 лет')])),
                ('value_first', models.IntegerField(blank=True, null=True)),
                ('value_last', models.IntegerField(blank=True, null=True)),
                ('bet', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_first', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volume_last', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coefficient_less_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coefficient_more_3', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Excise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_first_car', models.IntegerField(blank=True, null=True)),
                ('power_last_car', models.IntegerField(blank=True, null=True)),
                ('bet', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_first_car', models.IntegerField(blank=True, null=True)),
                ('price_last_car', models.IntegerField(blank=True, null=True)),
                ('price_transportation', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
