# Generated by Django 5.0.3 on 2024-03-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_car_data_alter_order_id_car_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('auc_link', models.TextField()),
                ('title', models.TextField()),
                ('auc_name', models.TextField()),
                ('auc_number', models.TextField()),
                ('auc_date', models.DateField()),
                ('year_car', models.TextField()),
                ('mileage', models.TextField()),
                ('color', models.TextField()),
                ('options', models.TextField()),
                ('the_body', models.TextField()),
                ('volume', models.TextField()),
                ('cpp', models.TextField()),
                ('estimation', models.TextField()),
                ('cooling', models.TextField()),
                ('set', models.TextField()),
                ('result', models.TextField()),
                ('start_price', models.TextField()),
                ('transmission', models.TextField()),
                ('location_auction', models.TextField()),
                ('year', models.TextField()),
                ('alt_color', models.TextField()),
                ('condition', models.TextField()),
                ('fuel', models.TextField()),
                ('equipment', models.TextField()),
                ('deadline_for_the_price_offer', models.TextField()),
                ('day_of_the_event', models.TextField()),
                ('number_of_sessions', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='id_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.car'),
        ),
        migrations.DeleteModel(
            name='Car_data',
        ),
    ]
