# Generated by Django 5.0.3 on 2024-03-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ptd',
            field=models.FileField(null=True, upload_to='media/ptd/'),
        ),
    ]
