# Generated by Django 5.0.3 on 2024-03-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_order_ptd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ptd',
            field=models.FileField(null=True, upload_to='ptd/'),
        ),
    ]
