# Generated by Django 5.0.3 on 2024-03-14 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_car_alter_order_id_car_delete_car_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_for_page',
            new_name='CarForPage',
        ),
        migrations.AddField(
            model_name='car',
            name='auc_list',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PhotoCar',
            fields=[
                ('id_photo', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField()),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.car')),
            ],
        ),
    ]
