# Generated by Django 5.0.3 on 2024-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_worker_password_alter_worker_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='job_title',
            field=models.TextField(choices=[('Клиент-менеджер', 'Менеджер'), ('Логист', 'Логист'), ('HR', 'HR'), ('Бухгалтер', 'Бухгалтер'), ('Оперативник', 'Оперативник')]),
        ),
    ]
