# Generated by Django 5.0.3 on 2024-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_worker_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='full_name',
            field=models.TextField(unique=True),
        ),
    ]
