# Generated by Django 5.0.3 on 2024-03-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_delete_carforpage_worker_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
