# Generated by Django 5.0.3 on 2024-03-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_remove_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='passport',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_number',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
