# Generated by Django 5.0.3 on 2024-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_worker_passport_worker_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='passport',
            field=models.TextField(unique=True),
        ),
    ]
