# Generated by Django 5.0.3 on 2024-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_rename_invoices_invoice_remove_customer_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(blank=True),
        ),
    ]
