# Generated by Django 5.0.3 on 2024-03-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_alter_order_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(),
        ),
    ]
